#!/bin/bash

## Author: Michel Heiniger
## Licence: GPL v3
## Description: A script to update a debian system over cron and log packages that been updated.

## Usage: apt-auto-update [options]
##
## Options:
#	-h, --help		Display description and options.
#	-v, --version	Display version of the script
#	-u,	--update	Perform a upgrade
##

VERSION='0.1'
MAIL='admin@domail.com'
LOGFILE='apt-update'
LOG='/var/log/mh-updater.log'
KERNEL_TARGET='linux'
TIMESTAMP=$(date +"[%a %d.%m.%Y - %H:%M:%S]")

kernel_update() {
	## TODO
	# - If there is a kernel update, a mail is send to the admin.
	# - Error handling
	apt-get -y upgrade > /dev/null 2>&1
	echo $TIMESTAMP 'There are kernel packages to upgrade. Packages upgraded: ' $UPDATE_LIST >> $LOG
	exit 0
}

normal_update() {
	## TODO
	# - Error handling
	apt-get -y upgrade > /dev/null 2>&1
	echo $TIMESTAMP 'Packages upgraded: ' $UPDATE_LIST >> $LOG
	exit 0
}

update() {
	#echo 'running the update' #debug

	apt-get update > /dev/null 2>&1

	# getting upgrade packages list
	UPDATE_LIST=$(apt-get -s dist-upgrade | awk '/^Inst/ { print $2 }' | tr '\n' ' ')
	
	# check if list is empty
	if [[ ! -z $UPDATE_LIST ]]; then
		# if yes: only non kernel related packages will be updated. (apt-get upgrade)
		# if no: packages will be updated. (apt-get dis-upgrade)
		if grep -q $KERNEL_TARGET <<< $UPDATE_LIST; then
			kernel_update
		else
			normal_update
		fi
	else
		echo $TIMESTAMP ' No updates found.' >> $LOG
		exit 0
	fi

	exit 1
}

case $1 in
-h|--help) echo 'le help message'; exit 0;;
-v|--version) echo 'version:' $VERSION; exit 0;;
-u|--update) update;;
*) update;;
esac
